CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE search_history (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    query character varying(64) NOT NULL,
    resolved_stock_code character varying(16),
    resolved_company_name character varying(128),
    searched_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_search_history" PRIMARY KEY ("Id")
);

CREATE TABLE summaries (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    stock_code character varying(16) NOT NULL,
    company_name character varying(128) NOT NULL,
    raw_data_json text NOT NULL,
    summary text NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_summaries" PRIMARY KEY ("Id")
);

CREATE INDEX idx_search_history_searched_at ON search_history (searched_at);

CREATE INDEX idx_summaries_expires_at ON summaries (expires_at);

CREATE INDEX idx_summaries_stock_code ON summaries (stock_code);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260829044525_InitialCreate', '8.0.10');

COMMIT;

