-- ============================================================
-- summaries.sql
-- 财报摘要缓存表（TTL 24h）
-- ============================================================

CREATE TABLE IF NOT EXISTS summaries (
"Id" integer GENERATED BY DEFAULT AS IDENTITY,
    stock_code character varying(16) NOT NULL,
    company_name character varying(128) NOT NULL,
    raw_data_json text NOT NULL,
    summary text NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_summaries" PRIMARY KEY ("Id")
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_summaries_expires_at ON summaries (expires_at);
CREATE INDEX IF NOT EXISTS idx_summaries_stock_code ON summaries (stock_code);
