-- ============================================================
-- search_history.sql
-- 搜索历史表（按 resolved_stock_code 去重）
-- ============================================================

CREATE TABLE IF NOT EXISTS search_history (
"Id" integer GENERATED BY DEFAULT AS IDENTITY,
    query character varying(64) NOT NULL,
    resolved_stock_code character varying(16),
    resolved_company_name character varying(128),
    searched_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_search_history" PRIMARY KEY ("Id")
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_search_history_searched_at ON search_history (searched_at);
